[workspace]
resolver = "3"
members = ["crates/agent", "crates/worker", "crates/cas", "crates/tracer", "crates/proto", "crates/dataplane", "crates/gui"]

[workspace.package]
version = "0.0.2"
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/SioKo-Shox3/Sembazuru"
publish = false
